### ISSUE TITLE
Help with the setup

### ISSUE THREAD

**Issue by larshelg** [roman01la/scrum.router#1]
Thanks for a great library :)

I'm trying to get this set up. But am struggling with a few things: 

This method: (r/start! routes) 
requires two params, the first param should be on-set-page, how do I define that.

Where is the atom that according to the doc is a scrum subscription?
This (rum/react r/router) seems to be a reference to bide's router function?

Also since r is used as a ref to bide namespace its a bit confusing when using r as a ref to the router namespace. 

NB I'm a clojurescript newbie if these questions seems silly. 

.lars

**Comment by roman01la** [comment]
@larshelg Hi. The router is outdated at the moment. It's compatible with Scrum 0.1.0-SNAPSHOT only. See [usage example](https://github.com/roman01la/scrum#usage) in Scrum's repo, it should be enough to get the idea. Hope it helps!
