### ISSUE TITLE
Example not updated to new Reconciler architecture in Scrum

### ISSUE THREAD

**Issue by VaclavSynacek** [roman01la/scrum.router#2]
It seems like the example has not been updated to use Reconciler architecture.

I am clojure newbie and am struggling to get the example running.
The requires at the beginning are probably wrong. After maybe fixing that (not sure I did) I get all sorts of other error that are probably related to missing Reconciler stuff in the example at all (for example `Wrong number of args (1) passed to scrum.core/broadcast!`)

**Comment by roman01la** [comment]
@VaclavSynacek Hi. I'd recommend to check out an example in Scrum's repo https://github.com/roman01la/scrum it is up to date. It lacks router example, but you will get the idea how it works.
